### ISSUE TITLE
[26/11/19] - Introdução ao GraphQL

### ISSUE THREAD

**Issue by NandoKstroNet** [pug-ma/quero-palestrar#2]
Título: **Introdução ao GraphQL**  
Palavras-chaves: `graphql`, `api`  
Nível: *básico*  
Palestrante: [**Nanderson Castro**](https://github.com/NandoKstroNet)
Descrição da palestra:
> Muito se têm falado do bendito GraphQL e sua popularidade vêm crescendo ao 
longos do anos, desde que o Facebook liberou ele publicamente. Uma das promessas do GraphQL é ser sucessor do REST trazendo assim requisições mais diretas e dinâmicas por meio de apenas uma chamada de endpoint. Nesta talk vamos conhecer o GraphQL e porque ele se propõe a substituir o REST.

Slides: [http://speakerdeck.com/nandokstronet](speakerdeck.com/nandokstronet)
Vídeo: [Playlist](http://bit.ly/graphql-curso)
GitHub: [http://github.com/CodeExpertsLearning/graphl-curso](http://github.com/CodeExpertsLearning/graphl-curso)

**Comment by schonfinkel** [comment]
Meetup confirmado na Owl Labs do CEUMA, das 19:00 - 21:00, dia 26/11/19.

**Comment by fredsonchaves07** [comment]
Já coloquei até na agenda aqui :)

**Comment by schonfinkel** [comment]
Palestra concluída em 26/11/19, material disponível nos links.
